#!/bin/bash

USER_NAME=chp
USER_PASS=chp

TABLE_SPACE_NAME=ts_$USER_NAME
DATE_FILE_NAME=ts_$USER_NAME.dbf
SYSTEM_PASSWORD=OraPwd11

sqlplus -s system/$SYSTEM_PASSWORD <<EOF
drop user $USER_NAME cascade;
drop tablespace $TABLE_SPACE_NAME including contents and datafiles;
exit
EOF

sqlplus -s system/$SYSTEM_PASSWORD <<EOF

CREATE TABLESPACE $TABLE_SPACE_NAME
    LOGGING
    DATAFILE '$DATE_FILE_NAME' SIZE 5M
    AUTOEXTEND  ON NEXT  20000K MAXSIZE  20000M EXTENT MANAGEMENT LOCAL
    SEGMENT SPACE MANAGEMENT  AUTO ;

CREATE USER $USER_NAME  PROFILE "DEFAULT"
    IDENTIFIED BY $USER_PASS DEFAULT TABLESPACE $TABLE_SPACE_NAME
    QUOTA UNLIMITED
    ON $TABLE_SPACE_NAME
    ACCOUNT UNLOCK;
GRANT "CONNECT" TO $USER_NAME  ;
GRANT "DBA" TO $USER_NAME;
exit
EOF
